# Generated by Django 6.0.6 on 2026-06-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_project_cover_image_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Local uploaded image (takes priority over URL)', null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL for the service card', max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text='Emoji fallback icon', max_length=100),
        ),
    ]
