# Generated by Django 5.1.2 on 2026-08-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_service_image_service_image_url_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
