# Generated by Django 5.1.2 on 2026-08-13 22:30

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_project_description_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='industry_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='backstory_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='mission_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='quality_policy_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='safety_statement_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='slogan_ar',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='what_we_do_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ar',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='caption_ar',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='safetypoint',
            name='text_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stat',
            name='label_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='suffufmeaning',
            name='word_ar',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Main cover image (Auto-converted to WEBP)', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='projects/covers/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='projects/gallery/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Uploaded image (Auto-converted to WEBP)', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='services/'),
        ),
    ]
